on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Start Redis
        run: |
          # Start Redis service
          redis-server --service-start

      - name: Run tests
        run: npm test