name: Run test cases

on: workflow_call

jobs:
  run-test-cases:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Setup Redis on Ubuntu
    - name: Setup Redis (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y redis-server
        sudo systemctl enable redis-server
        sudo systemctl start redis-server

    # Setup Redis on Windows using Memurai
    - name: Setup Redis (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install memurai -y
        Start-Process -NoNewWindow -FilePath "C:\Program Files\Memurai\memurai.exe"

    # Setup Redis on macOS
    - name: Setup Redis (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install redis
        brew services start redis

    - name: Install dependencies
      run: npm ci

    - name: Wait for Redis to be ready
      run: |
        for i in {1..10}; do
          if redis-cli ping | grep PONG; then
            echo "Redis is ready"
            exit 0
          fi
          echo "Waiting for Redis..."
          sleep 2
        done
        echo "Redis did not start in time"
        exit 1

    - name: Run tests
      run: npm test
      env:
        NODE_ENV: test

    - name: Upload coverage (Ubuntu + Node 18 only)
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x' && github.ref == 'refs/heads/main'
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
